### ISSUE TITLE
报“采集失败,标题匹配失败”

### ISSUE THREAD

**Issue by dingo826** [keepeye/diguoplugin_wxcrawl#1]
$html = request_get($postData['url']);
 preg_match('/<title>(.*)<\/title>/i',$html,$m);

这里报错，尝试了下语法没错，通过$html设置固定字符串测试成功。

**Comment by luwanming** [comment]
楼上的能说详细点吗？

**Comment by luwanming** [comment]
preg_match('/var msg_title = \"(.*)\"/i',$html,$m); 改成这句就可以了

**Comment by heihujiao0123** [comment]
您好，我使用了您的插件，感觉非常好。但是，在一些细节上稍微有一点问题，我把他完善了下。想把这个包给您，让您更新下。

**Comment by keepeye** [comment]
> 您好，我使用了您的插件，感觉非常好。但是，在一些细节上稍微有一点问题，我把他完善了下。想把这个包给您，让您更新下。

由于个人原因不再维护该项目，欢迎fork，自行修改
